epochs: 100
patience: 30
imgsz: 960
batch: 2
optimizer: AdamW
lr0: 0.0001
cos_lr: true
seed: 2026
device: '0'
workers: 4
degrees: 5.0
translate: 0.05
scale: 0.20
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.0
hsv_h: 0.015
hsv_s: 0.20
hsv_v: 0.20
mosaic: 0.20
close_mosaic: 10
mixup: 0.0
copy_paste: 0.0
erasing: 0.0
weight_decay: 0.0005
warmup_epochs: 3.0
amp: true
deterministic: true
